task1:
	gcc Task1.c -o Task1
task2:
	gcc Task2fork.c -o Task2fork
	gcc Task2exec.c -o Task2exec
task3:
	gcc Task3.c -o Task3
task4:
	gcc catcher.c -o catcher
	gcc sender.c -o sender
	gcc Catcher.c -o Catcher
	gcc Sender.c -o Sender
all:
	make task1
	make task2
	make task3
	make task4
clean:
	rm Task3
	rm catcher
	rm sender
	rm Catcher
	rm Sender
	rm Task1
	rm Task2fork
	rm Task2exec