Task1:
	gcc Interpreter.c -o interpret
Task2:
	gcc Sort.c -o sort
Task3:
	gcc Producer.c -o prod
	gcc Consumer.c -o cons
	gcc Executor.c -o executor
clean1:
	rm interpret
clean2:
	rm sort
clean3:
	rm prod
	rm cons
	rm executor
all:
	make Task1
	make Task2
	make Task3
clean:
	make clean1
	make clean2
	make clean3
