programs:
	gcc binaryDecoder.c -o bindecod
	gcc Matrix.c -o Matrix
	gcc ProcessTree.c -o tree
	gcc PasteExecutor.c -o pasteexec
cleanPrograms:
	rm bindecod
	rm Matrix
	rm tree
	rm pasteexec
cleanMatrixes:
	rm matrix*
